let top_gorssing_superhero_movies = [
    {
      "id": "top_grossing_superhero_0001",
      "name": "Avengers: Endgame",
      "synopsis": "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
      "releaseYear": "2019",
      "moviegenre": "Action, Adventure, Drama",
      "director": "Directors: Anthony Russo, Joe Russo",
      "cast": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
      "worldwidegross": "US$2.798 billion",
      "imdbRating": "8.4"
    },
    {
      "id": "top_grossing_superhero_0002",
      "name": "Avengers: Infinity War",
      "synopsis": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
      "releaseYear": "2018",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Directors: Anthony Russo, Joe Russo",
      "cast": "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans",
      "worldwidegross": "US$2.048 billion",
      "imdbRating": "8.4"
    },
    {
      "id": "top_grossing_superhero_0003",
      "name": "The Avengers",
      "synopsis": "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
      "releaseYear": "2012",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Joss Whedon",
      "cast": "Robert Downey Jr., Chris Evans, Scarlett Johansson, Jeremy Renner",
      "worldwidegross": "US$1.519 billion",
      "imdbRating": "8"
    },
    {
      "id": "top_grossing_superhero_0004",
      "name": "Avengers: Age of Ultron",
      "synopsis": "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
      "releaseYear": "2015",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Joss Whedon",
      "cast": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
      "worldwidegross": "US$1.403 billion",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_0005",
      "name": "Black Panther",
      "synopsis": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
      "releaseYear": "2018",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Ryan Coogler",
      "cast": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira",
      "worldwidegross": "US$1.347 billion",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_0006",
      "name": "Incredibles 2",
      "synopsis": "The Incredibles family takes on a new mission which involves a change in family roles: Bob Parr (Mr. Incredible) must manage the house while his wife Helen (Elastigirl) goes out to save the world.",
      "releaseYear": "2018",
      "moviegenre": "Animation, Action, Adventure",
      "director": "Brad Bird",
      "cast": "Craig T. Nelson, Holly Hunter, Sarah Vowell, Huck Milner",
      "worldwidegross": "US$1.243 billion",
      "imdbRating": "7.6"
    },
    {
      "id": "top_grossing_superhero_0007",
      "name": "Iron Man 3",
      "synopsis": "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
      "releaseYear": "2013",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Shane Black",
      "cast": "Robert Downey Jr., Guy Pearce, Gwyneth Paltrow, Don Cheadle",
      "worldwidegross": "US$1.215 billion",
      "imdbRating": "7.1"
    },
    {
      "id": "top_grossing_superhero_0008",
      "name": "Captain America: Civil War",
      "synopsis": "Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
      "releaseYear": "2016",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Directors: Anthony Russo, Joe Russo",
      "cast": "Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan",
      "worldwidegross": "US$1.153 billion",
      "imdbRating": "7.8"
    },
    {
      "id": "top_grossing_superhero_0009",
      "name": "Aquaman",
      "synopsis": "Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.",
      "releaseYear": "2018",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "James Wan",
      "cast": "Jason Momoa, Amber Heard, Willem Dafoe, Patrick Wilson",
      "worldwidegross": "US$1.148 billion",
      "imdbRating": "6.9"
    },
    {
      "id": "top_grossing_superhero_00010",
      "name": "Spider-Man: Far from Home",
      "synopsis": "Following the events of Avengers: Endgame (2019), Spider-Man must step up to take on new threats in a world that has changed forever.",
      "releaseYear": "2019",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Jon Watts",
      "cast": "Tom Holland, Samuel L. Jackson, Jake Gyllenhaal, Marisa Tomei",
      "worldwidegross": "US$1.132 billion",
      "imdbRating": "7.4"
    },
    {
      "id": "top_grossing_superhero_00011",
      "name": "Captain Marvel",
      "synopsis": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
      "releaseYear": "2019",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Directors: Anna Boden, Ryan Fleck",
      "cast": "Brie Larson, Samuel L. Jackson, Ben Mendelsohn, Jude Law",
      "worldwidegross": "US$1.128 billion",
      "imdbRating": "6.8"
    },
    {
      "id": "top_grossing_superhero_00012",
      "name": "The Dark Knight Rises",
      "synopsis": "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
      "releaseYear": "2012",
      "moviegenre": "Action",
      "director": "Christopher Nolan",
      "cast": "Christian Bale, Tom Hardy, Anne Hathaway, Gary Oldman",
      "worldwidegross": "US$1.081 billion",
      "imdbRating": "8.4"
    },
    {
      "id": "top_grossing_superhero_00013",
      "name": "The Dark Knight",
      "synopsis": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      "releaseYear": "2008",
      "moviegenre": "Action, Crime, Drama",
      "director": "Christopher Nolan",
      "cast": "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
      "worldwidegross": "US$1.038 billion",
      "imdbRating": "9"
    },
    {
      "id": "top_grossing_superhero_00014",
      "name": "Spider-Man 3",
      "synopsis": "A strange black entity from another world bonds with Peter Parker and causes inner turmoil as he contends with new villains, temptations, and revenge.",
      "releaseYear": "2007",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Sam Raimi",
      "cast": "Tobey Maguire, Kirsten Dunst, Topher Grace, Thomas Haden Church",
      "worldwidegross": "US$895 million",
      "imdbRating": "6.2"
    },
    {
      "id": "top_grossing_superhero_00015",
      "name": "Spider-Man: Homecoming",
      "synopsis": "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
      "releaseYear": "2017",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Jon Watts",
      "cast": "Tom Holland, Michael Keaton, Robert Downey Jr., Marisa Tomei",
      "worldwidegross": "US$880.1 million",
      "imdbRating": "7.4"
    },
    {
      "id": "top_grossing_superhero_00016",
      "name": "Batman v Superman: Dawn of Justice",
      "synopsis": "Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.",
      "releaseYear": "2016",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Zack Snyder",
      "cast": "Ben Affleck, Henry Cavill, Amy Adams, Jesse Eisenberg",
      "worldwidegross": "US$873.6 million",
      "imdbRating": "6.4"
    },
    {
      "id": "top_grossing_superhero_00017",
      "name": "Guardians of the Galaxy Vol. 2",
      "synopsis": "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego.",
      "releaseYear": "2017",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "James Gunn",
      "cast": "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel",
      "worldwidegross": "US$863.8 million",
      "imdbRating": "7.6"
    },
    {
      "id": "top_grossing_superhero_00018",
      "name": "Venom",
      "synopsis": "A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.",
      "releaseYear": "2018",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Ruben Fleischer",
      "cast": "Tom Hardy, Michelle Williams, Riz Ahmed, Scott Haze",
      "worldwidegross": "US$856.1 million",
      "imdbRating": "6.7"
    },
    {
      "id": "top_grossing_superhero_00019",
      "name": "Thor: Ragnarok",
      "synopsis": "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
      "releaseYear": "2017",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Taika Waititi",
      "cast": "Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Mark Ruffalo",
      "worldwidegross": "US$854 million",
      "imdbRating": "7.9"
    },
    {
      "id": "top_grossing_superhero_00020",
      "name": "Spider-Man",
      "synopsis": "When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.",
      "releaseYear": "2002",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Sam Raimi",
      "cast": "Tobey Maguire, Kirsten Dunst, Willem Dafoe, James Franco",
      "worldwidegross": "US$825 million",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_00021",
      "name": "Wonder Woman",
      "synopsis": "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",
      "releaseYear": "2017",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Patty Jenkins",
      "cast": "Gal Gadot, Chris Pine, Robin Wright, Lucy Davis",
      "worldwidegross": "US$821.8 million",
      "imdbRating": "7.4"
    },
    {
      "id": "top_grossing_superhero_00022",
      "name": "Spider-Man 2",
      "synopsis": "Peter Parker is beset with troubles in his failing personal life as he battles a brilliant scientist named Doctor Otto Octavius.",
      "releaseYear": "2004",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Sam Raimi",
      "cast": "Tobey Maguire, Kirsten Dunst, Alfred Molina, James Franco",
      "worldwidegross": "US$789 million",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_00023",
      "name": "Deadpool 2",
      "synopsis": "Foul-mouthed mutant mercenary Wade Wilson (a.k.a. Deadpool) assembles a team of fellow mutant rogues to protect a young boy with supernatural abilities from the brutal, time-traveling cyborg Cable.",
      "releaseYear": "2018",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "David Leitch",
      "cast": "Ryan Reynolds, Josh Brolin, Morena Baccarin, Julian Dennison",
      "worldwidegross": "US$785.8 million",
      "imdbRating": "7.7"
    },
    {
      "id": "top_grossing_superhero_00024",
      "name": "Deadpool",
      "synopsis": "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks.",
      "releaseYear": "2016",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Tim Miller",
      "cast": "Ryan Reynolds, Morena Baccarin, T.J. Miller, Ed Skrein",
      "worldwidegross": "US$782.6 million",
      "imdbRating": "8"
    },
    {
      "id": "top_grossing_superhero_00025",
      "name": "Guardians of the Galaxy",
      "synopsis": "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
      "releaseYear": "2014",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "James Gunn",
      "cast": "Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana",
      "worldwidegross": "US$772.8 million",
      "imdbRating": "8"
    },
    {
      "id": "top_grossing_superhero_00026",
      "name": "The Amazing Spider-Man",
      "synopsis": "After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.",
      "releaseYear": "2012",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Marc Webb",
      "cast": "Andrew Garfield, Emma Stone, Rhys Ifans, Irrfan Khan",
      "worldwidegross": "US$757.9 million",
      "imdbRating": "6.9"
    },
    {
      "id": "top_grossing_superhero_00027",
      "name": "Suicide Squad",
      "synopsis": "A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.",
      "releaseYear": "2016",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "David Ayer",
      "cast": "Will Smith, Jared Leto, Margot Robbie, Viola Davis",
      "worldwidegross": "US$746.8 million",
      "imdbRating": "5.9"
    },
    {
      "id": "top_grossing_superhero_00028",
      "name": "X-Men: Days of Future Past",
      "synopsis": "The X-Men send Wolverine to the past in a desperate effort to change history and prevent an event that results in doom for both humans and mutants.",
      "releaseYear": "2014",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Bryan Singer",
      "cast": "Patrick Stewart, Ian McKellen, Hugh Jackman, James McAvoy",
      "worldwidegross": "US$746 million",
      "imdbRating": "7.9"
    },
    {
      "id": "top_grossing_superhero_00029",
      "name": "The Matrix Reloaded",
      "synopsis": "Freedom fighters Neo, Trinity and Morpheus continue to lead the revolt against the Machine Army, unleashing their arsenal of extraordinary skills and weaponry against the systematic forces of repression and exploitation.",
      "releaseYear": "2003",
      "moviegenre": "Action, Sci-Fi",
      "director": "Directors: Lana Wachowski, Lilly Wachowski",
      "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
      "worldwidegross": "US$741.8 million",
      "imdbRating": "7.2"
    },
    {
      "id": "top_grossing_superhero_00030",
      "name": "Captain America: The Winter Soldier",
      "synopsis": "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.",
      "releaseYear": "2014",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Directors: Anthony Russo, Joe Russo",
      "cast": "Chris Evans, Samuel L. Jackson, Scarlett Johansson, Robert Redford",
      "worldwidegross": "US$714.4 million",
      "imdbRating": "7.7"
    },
    {
      "id": "top_grossing_superhero_00031",
      "name": "The Amazing Spider-Man 2",
      "synopsis": "When New York is put under siege by Oscorp, it is up to Spider-Man to save the city he swore to protect as well as his loved ones.",
      "releaseYear": "2014",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Marc Webb",
      "cast": "Andrew Garfield, Emma Stone, Jamie Foxx, Paul Giamatti",
      "worldwidegross": "US$709 million",
      "imdbRating": "6.6"
    },
    {
      "id": "top_grossing_superhero_00032",
      "name": "Doctor Strange",
      "synopsis": "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
      "releaseYear": "2016",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Scott Derrickson",
      "cast": "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Benedict Wong",
      "worldwidegross": "US$677.7 million",
      "imdbRating": "7.5"
    },
    {
      "id": "top_grossing_superhero_00033",
      "name": "Man of Steel",
      "synopsis": "An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened, when other survivors of his home planet invade Earth.",
      "releaseYear": "2013",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Zack Snyder",
      "cast": "Henry Cavill, Amy Adams, Michael Shannon, Diane Lane",
      "worldwidegross": "US$668 million",
      "imdbRating": "7"
    },
    {
      "id": "top_grossing_superhero_00034",
      "name": "Justice League",
      "synopsis": "Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his new-found ally, Diana Prince, to face an even greater enemy.",
      "releaseYear": "2017",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Zack Snyder",
      "cast": "Ben Affleck, Gal Gadot, Jason Momoa, Ezra Miller",
      "worldwidegross": "US$657.9 million",
      "imdbRating": "6.1"
    },
    {
      "id": "top_grossing_superhero_00035",
      "name": "Big Hero 6",
      "synopsis": "A special bond develops between plus-sized inflatable robot Baymax and prodigy Hiro Hamada, who together team up with a group of friends to form a band of high-tech heroes.",
      "releaseYear": "2014",
      "moviegenre": "Animation, Action, Adventure",
      "director": "Directors: Don Hall, Chris Williams",
      "cast": "Ryan Potter, Scott Adsit, Jamie Chung, T.J. Miller",
      "worldwidegross": "US$657.8 million",
      "imdbRating": "7.8"
    },
    {
      "id": "top_grossing_superhero_00036",
      "name": "Thor: The Dark World",
      "synopsis": "When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous and personal journey that will reunite him with doctor Jane Foster.",
      "releaseYear": "2013",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Alan Taylor",
      "cast": "Chris Hemsworth, Natalie Portman, Tom Hiddleston, Stellan Skarsgård",
      "worldwidegross": "US$644.8 million",
      "imdbRating": "6.8"
    },
    {
      "id": "top_grossing_superhero_00037",
      "name": "The Incredibles",
      "synopsis": "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.",
      "releaseYear": "2004",
      "moviegenre": "Animation, Action, Adventure",
      "director": "Brad Bird",
      "cast": "Craig T. Nelson, Samuel L. Jackson, Holly Hunter, Jason Lee",
      "worldwidegross": "US$631.6 million",
      "imdbRating": "8"
    },
    {
      "id": "top_grossing_superhero_00038",
      "name": "Hancock",
      "synopsis": "Hancock is a superhero whose ill-considered behavior regularly causes damage in the millions. He changes when the person he saves helps him improve his public image.",
      "releaseYear": "2008",
      "moviegenre": "Action, Drama, Fantasy",
      "director": "Peter Berg",
      "cast": "Will Smith, Charlize Theron, Jason Bateman, Jae Head",
      "worldwidegross": "US$629.4 million",
      "imdbRating": "6.4"
    },
    {
      "id": "top_grossing_superhero_00039",
      "name": "Iron Man 2",
      "synopsis": "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.",
      "releaseYear": "2010",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Jon Favreau",
      "cast": "Robert Downey Jr., Mickey Rourke, Gwyneth Paltrow, Don Cheadle",
      "worldwidegross": "US$623.9 million",
      "imdbRating": "7"
    },
    {
      "id": "top_grossing_superhero_00040",
      "name": "Ant-Man and the Wasp",
      "synopsis": "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
      "releaseYear": "2018",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Peyton Reed",
      "cast": "Paul Rudd, Evangeline Lilly, Michael Peña, Walton Goggins",
      "worldwidegross": "US$622.7 million",
      "imdbRating": "7"
    },
    {
      "id": "top_grossing_superhero_00041",
      "name": "Logan",
      "synopsis": "In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.",
      "releaseYear": "2017",
      "moviegenre": "Action, Drama, Sci-Fi",
      "director": "James Mangold",
      "cast": "Hugh Jackman, Patrick Stewart, Dafne Keen, Boyd Holbrook",
      "worldwidegross": "US$619 million",
      "imdbRating": "8.1"
    },
    {
      "id": "top_grossing_superhero_00042",
      "name": "Iron Man",
      "synopsis": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
      "releaseYear": "2008",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Jon Favreau",
      "cast": "Robert Downey Jr., Gwyneth Paltrow, Terrence Howard, Jeff Bridges",
      "worldwidegross": "US$585.4 million",
      "imdbRating": "7.9"
    },
    {
      "id": "top_grossing_superhero_00043",
      "name": "X-Men: Apocalypse",
      "synopsis": "In the 1980s the X-Men must defeat an ancient all-powerful mutant, En Sabah Nur, who intends to thrive through bringing destruction to the world.",
      "releaseYear": "2016",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Bryan Singer",
      "cast": "James McAvoy, Michael Fassbender, Jennifer Lawrence, Nicholas Hoult",
      "worldwidegross": "US$543.9 million",
      "imdbRating": "6.9"
    },
    {
      "id": "top_grossing_superhero_00044",
      "name": "Ant-Man",
      "synopsis": "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, pull off a plan that will save the world.",
      "releaseYear": "2015",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Peyton Reed",
      "cast": "Paul Rudd, Michael Douglas, Corey Stoll, Evangeline Lilly",
      "worldwidegross": "US$519.3 million",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_00045",
      "name": "Teenage Mutant Ninja Turtles",
      "synopsis": "When a kingpin threatens New York City, a group of mutated turtle warriors must emerge from the shadows to protect their home.",
      "releaseYear": "2014",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Jonathan Liebesman",
      "cast": "Megan Fox, Will Arnett, William Fichtner, Noel Fisher",
      "worldwidegross": "US$485 million",
      "imdbRating": "5.8"
    },
    {
      "id": "top_grossing_superhero_00046",
      "name": "The Matrix",
      "synopsis": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
      "releaseYear": "1999",
      "moviegenre": "Action, Sci-Fi",
      "director": "Directors: Lana Wachowski, Lilly Wachowski",
      "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
      "worldwidegross": "US$465.3 million",
      "imdbRating": "8.7"
    },
    {
      "id": "top_grossing_superhero_00047",
      "name": "X-Men: The Last Stand",
      "synopsis": "The human government develops a cure for mutations, and Jean Gray becomes a darker uncontrollable persona called the Phoenix who allies with Magneto, causing escalation into an all-out battle for the X-Men.",
      "releaseYear": "2006",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Brett Ratner",
      "cast": "Patrick Stewart, Hugh Jackman, Halle Berry, Famke Janssen",
      "worldwidegross": "US$460.4 million",
      "imdbRating": "6.7"
    },
    {
      "id": "top_grossing_superhero_00048",
      "name": "Thor",
      "synopsis": "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.",
      "releaseYear": "2011",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Kenneth Branagh",
      "cast": "Chris Hemsworth, Anthony Hopkins, Natalie Portman, Tom Hiddleston",
      "worldwidegross": "US$449.3 million",
      "imdbRating": "7"
    },
    {
      "id": "top_grossing_superhero_00049",
      "name": "The Matrix Revolutions",
      "synopsis": "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
      "releaseYear": "2003",
      "moviegenre": "Action, Sci-Fi",
      "director": "Directors: Lana Wachowski, Lilly Wachowski",
      "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
      "worldwidegross": "US$427.3 million",
      "imdbRating": "6.8"
    },
    {
      "id": "top_grossing_superhero_00050",
      "name": "The Wolverine",
      "synopsis": "Wolverine comes to Japan to meet an old friend whose life he saved years ago, and gets embroiled in a conspiracy involving yakuza and mutants.",
      "releaseYear": "2013",
      "moviegenre": "Action, Sci-Fi",
      "director": "James Mangold",
      "cast": "Hugh Jackman, Will Yun Lee, Tao Okamoto, Rila Fukushima",
      "worldwidegross": "US$414.8 million",
      "imdbRating": "6.7"
    },
    {
      "id": "top_grossing_superhero_00051",
      "name": "Batman",
      "synopsis": "The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.",
      "releaseYear": "1989",
      "moviegenre": "Action, Adventure",
      "director": "Tim Burton",
      "cast": "Michael Keaton, Jack Nicholson, Kim Basinger, Robert Wuhl",
      "worldwidegross": "US$411.6 million",
      "imdbRating": "7.5"
    },
    {
      "id": "top_grossing_superhero_00052",
      "name": "X2: X-Men United",
      "synopsis": "When anti-mutant Colonel William Stryker kidnaps Professor X and attacks his school, the X-Men must ally with their archenemy Magneto to stop him.",
      "releaseYear": "2003",
      "moviegenre": "Action, Sci-Fi, Thriller",
      "director": "Bryan Singer",
      "cast": "Patrick Stewart, Hugh Jackman, Halle Berry, Ian McKellen",
      "worldwidegross": "US$407.7 million",
      "imdbRating": "7.4"
    },
    {
      "id": "top_grossing_superhero_00053",
      "name": "Superman Returns",
      "synopsis": "Superman returns to Earth after spending five years in space examining his homeworld Krypton. But he finds things have changed while he was gone, and he must once again prove himself important to the world.",
      "releaseYear": "2006",
      "moviegenre": "Action, Sci-Fi",
      "director": "Bryan Singer",
      "cast": "Brandon Routh, Kevin Spacey, Kate Bosworth, James Marsden",
      "worldwidegross": "US$391.1 million",
      "imdbRating": "6"
    },
    {
      "id": "top_grossing_superhero_00054",
      "name": "Batman Begins",
      "synopsis": "After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.",
      "releaseYear": "2005",
      "moviegenre": "Action, Adventure",
      "director": "Christopher Nolan",
      "cast": "Christian Bale, Michael Caine, Ken Watanabe, Liam Neeson",
      "worldwidegross": "US$379.7 million",
      "imdbRating": "8.2"
    },
    {
      "id": "top_grossing_superhero_00055",
      "name": "Black Widow",
      "synopsis": "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
      "releaseYear": "2021",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Cate Shortland",
      "cast": "Scarlett Johansson, Florence Pugh, David Harbour, Rachel Weisz",
      "worldwidegross": "US$378.4 million",
      "imdbRating": "6.8"
    },
    {
      "id": "top_grossing_superhero_00056",
      "name": "Spider-Man: Into the Spider-Verse",
      "synopsis": "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
      "releaseYear": "2018",
      "moviegenre": "Animation, Action, Adventure",
      "director": "Directors: Bob Persichetti, Peter Ramsey, Rodney Rothman",
      "cast": "Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali",
      "worldwidegross": "US$375.5 million",
      "imdbRating": "8.4"
    },
    {
      "id": "top_grossing_superhero_00057",
      "name": "X-Men Origins: Wolverine",
      "synopsis": "The early years of James Logan, featuring his rivalry with his brother Victor Creed, his service in the special forces team Weapon X, and his experimentation into the metal-lined mutant Wolverine.",
      "releaseYear": "2009",
      "moviegenre": "Action, Sci-Fi",
      "director": "Gavin Hood",
      "cast": "Hugh Jackman, Liev Schreiber, Ryan Reynolds, Danny Huston",
      "worldwidegross": "US$373.1 million",
      "imdbRating": "6.6"
    },
    {
      "id": "top_grossing_superhero_00058",
      "name": "Captain America: The First Avenger",
      "synopsis": "Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a \"Super-Soldier serum\". But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.",
      "releaseYear": "2011",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Joe Johnston",
      "cast": "Chris Evans, Hugo Weaving, Samuel L. Jackson, Hayley Atwell",
      "worldwidegross": "US$370.6 million",
      "imdbRating": "6.9"
    },
    {
      "id": "top_grossing_superhero_00059",
      "name": "Shazam!",
      "synopsis": "A newly fostered young boy in search of his mother instead finds unexpected super powers and soon gains a powerful enemy.",
      "releaseYear": "2019",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "David F. Sandberg",
      "cast": "Zachary Levi, Mark Strong, Asher Angel, Jack Dylan Grazer",
      "worldwidegross": "US$366 million",
      "imdbRating": "7"
    },
    {
      "id": "top_grossing_superhero_00060",
      "name": "Shang-Chi and the Legend of the Ten Rings",
      "synopsis": "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
      "releaseYear": "2021",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Destin Daniel Cretton",
      "cast": "Simu Liu, Awkwafina, Tony Chiu-Wai Leung, Ben Kingsley",
      "worldwidegross": "US$363.4 million (still running)",
      "imdbRating": "7.9"
    },
    {
      "id": "top_grossing_superhero_00061",
      "name": "X-Men: First Class",
      "synopsis": "In the 1960s, superpowered humans Charles Xavier and Erik Lensherr work together to find others like them, but Erik's vengeful pursuit of an ambitious mutant who ruined his life causes a schism to divide them.",
      "releaseYear": "2011",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Matthew Vaughn",
      "cast": "James McAvoy, Michael Fassbender, Jennifer Lawrence, Kevin Bacon",
      "worldwidegross": "US$352.6 million",
      "imdbRating": "7.7"
    },
    {
      "id": "top_grossing_superhero_00062",
      "name": "The Mask",
      "synopsis": "Bank clerk Stanley Ipkiss is transformed into a manic superhero when he wears a mysterious mask.",
      "releaseYear": "1994",
      "moviegenre": "Action, Comedy, Crime",
      "director": "Chuck Russell",
      "cast": "Jim Carrey, Cameron Diaz, Peter Riegert, Peter Greene",
      "worldwidegross": "US$351.6 million",
      "imdbRating": "6.9"
    },
    {
      "id": "top_grossing_superhero_00063",
      "name": "Batman Forever",
      "synopsis": "Batman must battle former district attorney Harvey Dent, who is now Two-Face and Edward Nygma, The Riddler with help from an amorous psychologist and a young circus acrobat who becomes his sidekick, Robin.",
      "releaseYear": "1995",
      "moviegenre": "Action, Adventure",
      "director": "Joel Schumacher",
      "cast": "Val Kilmer, Tommy Lee Jones, Jim Carrey, Nicole Kidman",
      "worldwidegross": "US$336.6 million",
      "imdbRating": "5.4"
    },
    {
      "id": "top_grossing_superhero_00064",
      "name": "Fantastic Four",
      "synopsis": "A group of astronauts gain superpowers after a cosmic radiation exposure and must use them to oppose the plans of their enemy, Doctor Victor Von Doom.",
      "releaseYear": "I (2005)",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Tim Story",
      "cast": "Ioan Gruffudd, Michael Chiklis, Chris Evans, Jessica Alba",
      "worldwidegross": "US$333.5 million",
      "imdbRating": "5.7"
    },
    {
      "id": "top_grossing_superhero_00065",
      "name": "Sonic the Hedgehog",
      "synopsis": "After discovering a small, blue, fast hedgehog, a small-town police officer must help him defeat an evil genius who wants to do experiments on him.",
      "releaseYear": "2020",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Jeff Fowler",
      "cast": "Ben Schwartz, James Marsden, Jim Carrey, Tika Sumpter",
      "worldwidegross": "US$319.7 million",
      "imdbRating": "6.5"
    },
    {
      "id": "top_grossing_superhero_00066",
      "name": "The Lego Batman Movie",
      "synopsis": "A cooler-than-ever Bruce Wayne must deal with the usual suspects as they plan to rule Gotham City, while discovering that he has accidentally adopted a teenage orphan who wishes to become his sidekick.",
      "releaseYear": "2017",
      "moviegenre": "Animation, Action, Adventure",
      "director": "Chris McKay",
      "cast": "Will Arnett, Michael Cera, Rosario Dawson, Ralph Fiennes",
      "worldwidegross": "US$312 million",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_00067",
      "name": "Fantastic 4: Rise of the Silver Surfer",
      "synopsis": "The Fantastic Four learn that they aren't the only super-powered beings in the universe when they square off against the powerful Silver Surfer and the planet-eating Galactus.",
      "releaseYear": "2007",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Tim Story",
      "cast": "Ioan Gruffudd, Jessica Alba, Chris Evans, Michael Chiklis",
      "worldwidegross": "US$301.9 million",
      "imdbRating": "5.6"
    },
    {
      "id": "top_grossing_superhero_00068",
      "name": "Superman",
      "synopsis": "An alien orphan is sent from his dying planet to Earth, where he grows up to become his adoptive home's first and greatest superhero.",
      "releaseYear": "1978",
      "moviegenre": "Action, Adventure, Drama",
      "director": "Richard Donner",
      "cast": "Christopher Reeve, Margot Kidder, Gene Hackman, Marlon Brando",
      "worldwidegross": "US$300.5 million",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_00069",
      "name": "X-Men",
      "synopsis": "In a world where mutants (evolved super-powered humans) exist and are discriminated against, two groups form for an inevitable clash: the supremacist Brotherhood, and the pacifist X-Men.",
      "releaseYear": "2000",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Bryan Singer",
      "cast": "Patrick Stewart, Hugh Jackman, Ian McKellen, Famke Janssen",
      "worldwidegross": "US$296.3 million",
      "imdbRating": "7.4"
    },
    {
      "id": "top_grossing_superhero_00070",
      "name": "Split",
      "synopsis": "Three girls are kidnapped by a man with a diagnosed 23 distinct personalities. They must try to escape before the apparent emergence of a frightful new 24th.",
      "releaseYear": "IX (2016)",
      "moviegenre": "Horror, Thriller",
      "director": "M. Night Shyamalan",
      "cast": "James McAvoy, Anya Taylor-Joy, Haley Lu Richardson, Jessica Sula",
      "worldwidegross": "US$278.5 million",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_00071",
      "name": "Batman Returns",
      "synopsis": "While Batman deals with a deformed man calling himself the Penguin wreaking havoc across Gotham with the help of a cruel businessman, a female employee of the latter becomes the Catwoman with her own vendetta.",
      "releaseYear": "1992",
      "moviegenre": "Action, Crime, Fantasy",
      "director": "Tim Burton",
      "cast": "Michael Keaton, Danny DeVito, Michelle Pfeiffer, Christopher Walken",
      "worldwidegross": "US$266.9 million",
      "imdbRating": "7"
    },
    {
      "id": "top_grossing_superhero_00072",
      "name": "The Incredible Hulk",
      "synopsis": "Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into whenever he loses his temper.",
      "releaseYear": "2008",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Louis Leterrier",
      "cast": "Edward Norton, Liv Tyler, Tim Roth, William Hurt",
      "worldwidegross": "US$264.8 million",
      "imdbRating": "6.6"
    },
    {
      "id": "top_grossing_superhero_00073",
      "name": "X-Men: Dark Phoenix",
      "synopsis": "Jean Grey begins to develop incredible powers that corrupt and turn her into a Dark Phoenix, causing the X-Men to decide if her life is worth more than all of humanity.",
      "releaseYear": "2019",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Simon Kinberg",
      "cast": "James McAvoy, Michael Fassbender, Jennifer Lawrence, Nicholas Hoult",
      "worldwidegross": "US$252.4 million",
      "imdbRating": "5.7"
    },
    {
      "id": "top_grossing_superhero_00074",
      "name": "Unbreakable",
      "synopsis": "A man learns something extraordinary about himself after a devastating accident.",
      "releaseYear": "2000",
      "moviegenre": "Drama, Mystery, Sci-Fi",
      "director": "M. Night Shyamalan",
      "cast": "Bruce Willis, Samuel L. Jackson, Robin Wright, Spencer Treat Clark",
      "worldwidegross": "US$248.1 million",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_00075",
      "name": "Glass",
      "synopsis": "Security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities.",
      "releaseYear": "2019",
      "moviegenre": "Drama, Sci-Fi, Thriller",
      "director": "M. Night Shyamalan",
      "cast": "James McAvoy, Bruce Willis, Samuel L. Jackson, Anya Taylor-Joy",
      "worldwidegross": "US$247 million",
      "imdbRating": "6.6"
    },
    {
      "id": "top_grossing_superhero_00076",
      "name": "Teenage Mutant Ninja Turtles: Out of the Shadows",
      "synopsis": "The Turtles get into another battle with their enemy the Shredder, who has acquired new allies: the mutant thugs Bebop and Rocksteady and the alien being Krang.",
      "releaseYear": "2016",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Dave Green",
      "cast": "Megan Fox, Will Arnett, Tyler Perry, Laura Linney",
      "worldwidegross": "US$245.6 million",
      "imdbRating": "6"
    },
    {
      "id": "top_grossing_superhero_00077",
      "name": "Hulk",
      "synopsis": "Bruce Banner, a genetics researcher with a tragic past, suffers an accident that causes him to transform into a raging green monster when he gets angry.",
      "releaseYear": "2003",
      "moviegenre": "Action, Sci-Fi",
      "director": "Ang Lee",
      "cast": "Eric Bana, Jennifer Connelly, Sam Elliott, Josh Lucas",
      "worldwidegross": "US$245.3 million",
      "imdbRating": "5.6"
    },
    {
      "id": "top_grossing_superhero_00078",
      "name": "Batman & Robin",
      "synopsis": "Batman and Robin try to keep their relationship together even as they must stop Mr. Freeze and Poison Ivy from freezing Gotham City.",
      "releaseYear": "1997",
      "moviegenre": "Action, Sci-Fi",
      "director": "Joel Schumacher",
      "cast": "Arnold Schwarzenegger, George Clooney, Chris O'Donnell, Uma Thurman",
      "worldwidegross": "US$238.2 million",
      "imdbRating": "3.8"
    },
    {
      "id": "top_grossing_superhero_00079",
      "name": "Ghost Rider",
      "synopsis": "When motorcycle rider Johnny Blaze sells his soul to the Devil to save his father's life, he is transformed into the Ghost Rider, the Devil's own bounty hunter, and is sent to hunt down sinners.",
      "releaseYear": "2007",
      "moviegenre": "Action, Fantasy, Thriller",
      "director": "Mark Steven Johnson",
      "cast": "Nicolas Cage, Eva Mendes, Sam Elliott, Matt Long",
      "worldwidegross": "US$228.7 million",
      "imdbRating": "5.3"
    },
    {
      "id": "top_grossing_superhero_00080",
      "name": "The Green Hornet",
      "synopsis": "Following the death of his father, Britt Reid, heir to his father's large company, teams up with his late dad's assistant Kato to become a masked crime fighting team.",
      "releaseYear": "2011",
      "moviegenre": "Action, Comedy, Crime",
      "director": "Michel Gondry",
      "cast": "Seth Rogen, Jay Chou, Christoph Waltz, Cameron Diaz",
      "worldwidegross": "US$227.8 million",
      "imdbRating": "5.8"
    },
    {
      "id": "top_grossing_superhero_00081",
      "name": "Green Lantern",
      "synopsis": "Reckless test pilot Hal Jordan is granted an alien ring that bestows him with otherworldly powers that inducts him into an intergalactic police force, the Green Lantern Corps.",
      "releaseYear": "2011",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Martin Campbell",
      "cast": "Ryan Reynolds, Blake Lively, Peter Sarsgaard, Mark Strong",
      "worldwidegross": "US$219.9 million",
      "imdbRating": "5.5"
    },
    {
      "id": "top_grossing_superhero_00082",
      "name": "Teenage Mutant Ninja Turtles: The Movie",
      "synopsis": "Four teenage mutant ninja turtles emerge from the shadows to protect New York City from a gang of criminal ninjas.",
      "releaseYear": "1990",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Steve Barron",
      "cast": "Judith Hoag, Elias Koteas, Josh Pais, David Forman",
      "worldwidegross": "US$202 million",
      "imdbRating": "6.8"
    },
    {
      "id": "top_grossing_superhero_00083",
      "name": "Birds of Prey",
      "synopsis": "After splitting with the Joker, Harley Quinn joins superheroes Black Canary, Huntress and Renee Montoya to save a young girl from an evil crime lord.",
      "releaseYear": "2020",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "Cathy Yan",
      "cast": "Margot Robbie, Rosie Perez, Mary Elizabeth Winstead, Jurnee Smollett",
      "worldwidegross": "US$201.9 million",
      "imdbRating": "6.1"
    },
    {
      "id": "top_grossing_superhero_00084",
      "name": "Superman II",
      "synopsis": "Superman agrees to sacrifice his powers to start a relationship with Lois Lane, unaware that three Kryptonian criminals he inadvertently released are conquering Earth.",
      "releaseYear": "1980",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Directors: Richard Lester, Richard Donner",
      "cast": "Gene Hackman, Christopher Reeve, Margot Kidder, Ned Beatty",
      "worldwidegross": "US$190.4 million",
      "imdbRating": "6.8"
    },
    {
      "id": "top_grossing_superhero_00085",
      "name": "Watchmen",
      "synopsis": "In 1985 where former superheroes exist, the murder of a colleague sends active vigilante Rorschach into his own sprawling investigation, uncovering something that could completely change the course of history as we know it.",
      "releaseYear": "2009",
      "moviegenre": "Action, Drama, Mystery",
      "director": "Zack Snyder",
      "cast": "Jackie Earle Haley, Patrick Wilson, Carla Gugino, Malin Akerman",
      "worldwidegross": "US$185.4 million",
      "imdbRating": "7.6"
    },
    {
      "id": "top_grossing_superhero_00086",
      "name": "The League of Extraordinary Gentlemen",
      "synopsis": "In an alternate Victorian Age world, a group of famous contemporary fantasy, science fiction, and adventure characters team up on a secret mission.",
      "releaseYear": "2003",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Stephen Norrington",
      "cast": "Sean Connery, Stuart Townsend, Peta Wilson, Jason Flemyng",
      "worldwidegross": "US$179.3 million",
      "imdbRating": "5.8"
    },
    {
      "id": "top_grossing_superhero_00087",
      "name": "Daredevil",
      "synopsis": "A man blinded by toxic waste which also enhanced his remaining senses fights crime as an acrobatic martial arts superhero.",
      "releaseYear": "2003",
      "moviegenre": "Action, Crime",
      "director": "Mark Steven Johnson",
      "cast": "Ben Affleck, Jennifer Garner, Colin Farrell, Michael Clarke Duncan",
      "worldwidegross": "US$179.2 million",
      "imdbRating": "5.3"
    },
    {
      "id": "top_grossing_superhero_00088",
      "name": "Hellboy II: The Golden Army",
      "synopsis": "A prince of the mythical world starts a rebellion against humanity in order to rule the Earth, and Hellboy his team must fight to stop him from locating the all-powerful Golden Army.",
      "releaseYear": "2008",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Guillermo del Toro",
      "cast": "Ron Perlman, Selma Blair, Doug Jones, John Alexander",
      "worldwidegross": "US$168.3 million",
      "imdbRating": "7"
    },
    {
      "id": "top_grossing_superhero_00089",
      "name": "Fantastic Four",
      "synopsis": "Four young outsiders teleport to an alternate and dangerous universe which alters their physical form in shocking ways. The four must learn to harness their new abilities and work together to save Earth from a former friend turned enemy.",
      "releaseYear": "2015",
      "moviegenre": "Action, Adventure, Sci-Fi",
      "director": "Directors: Josh Trank, Stephen E. Rivkin",
      "cast": "Miles Teller, Kate Mara, Michael B. Jordan, Jamie Bell",
      "worldwidegross": "US$167.9 million",
      "imdbRating": "4.2"
    },
    {
      "id": "top_grossing_superhero_00090",
      "name": "The Suicide Squad",
      "synopsis": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
      "releaseYear": "2021",
      "moviegenre": "Action, Adventure, Comedy",
      "director": "James Gunn",
      "cast": "Margot Robbie, Idris Elba, John Cena, Joel Kinnaman",
      "worldwidegross": "US$167.3 million",
      "imdbRating": "7.3"
    },
    {
      "id": "top_grossing_superhero_00091",
      "name": "Wonder Woman 1984",
      "synopsis": "Diana must contend with a work colleague and businessman, whose desire for extreme wealth sends the world down a path of destruction, after an ancient artifact that grants wishes goes missing.",
      "releaseYear": "2020",
      "moviegenre": "Action, Adventure, Fantasy",
      "director": "Patty Jenkins",
      "cast": "Gal Gadot, Chris Pine, Kristen Wiig, Pedro Pascal",
      "worldwidegross": "US$164 million",
      "imdbRating": "5.4"
    },
    {
      "id": "top_grossing_superhero_00092",
      "name": "Dick Tracy",
      "synopsis": "The comic strip detective finds his life vastly complicated when Breathless Mahoney makes advances towards him while he is trying to battle Big Boy Caprice's united mob.",
      "releaseYear": "1990",
      "moviegenre": "Action, Comedy, Crime",
      "director": "Warren Beatty",
      "cast": "Warren Beatty, Madonna, Al Pacino, Charlie Korsmo",
      "worldwidegross": "US$162.7 million",
      "imdbRating": "6.1"
    },
    {
      "id": "top_grossing_superhero_00093",
      "name": "Blade II",
      "synopsis": "Blade forms an uneasy alliance with the vampire council in order to combat the Reapers, who are feeding on vampires.",
      "releaseYear": "2002",
      "moviegenre": "Action, Horror, Sci-Fi",
      "director": "Guillermo del Toro",
      "cast": "Wesley Snipes, Kris Kristofferson, Ron Perlman, Leonor Varela",
      "worldwidegross": "US$155 million",
      "imdbRating": "6.7"
    },
    {
      "id": "top_grossing_superhero_00094",
      "name": "Ghost Rider: Spirit of Vengeance",
      "synopsis": "Johnny Blaze, tortured by the Ghost Rider's curse, gets a chance of redemption through protecting the Devil's son, whose father is pursuing him.",
      "releaseYear": "2011",
      "moviegenre": "Action, Fantasy, Thriller",
      "director": "Directors: Mark Neveldine, Brian Taylor",
      "cast": "Nicolas Cage, Ciarán Hinds, Idris Elba, Violante Placido",
      "worldwidegross": "US$132.6 million",
      "imdbRating": "4.3"
    },
    {
      "id": "top_grossing_superhero_00095",
      "name": "Blade: Trinity",
      "synopsis": "Blade, now a wanted man by the FBI, must join forces with the Nightstalkers to face his most challenging enemy yet: Dracula.",
      "releaseYear": "2004",
      "moviegenre": "Action, Horror, Sci-Fi",
      "director": "David S. Goyer",
      "cast": "Wesley Snipes, Kris Kristofferson, Parker Posey, Ryan Reynolds",
      "worldwidegross": "US$132 million",
      "imdbRating": "5.8"
    },
    {
      "id": "top_grossing_superhero_00096",
      "name": "Blade",
      "synopsis": "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
      "releaseYear": "1998",
      "moviegenre": "Action, Horror, Sci-Fi",
      "director": "Stephen Norrington",
      "cast": "Wesley Snipes, Stephen Dorff, Kris Kristofferson, N'Bushe Wright",
      "worldwidegross": "US$131.2 million",
      "imdbRating": "7.1"
    }
  ]