let top_grossing_telugu_movies = 
    [
        {
          "id": "top_grossing_telugu_000101",
          "name": "Baahubali 2: The Conclusion",
          "synopsis": "When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.",
          "releaseYear": "2017",
          "moviegenre": "Action, Drama",
          "director": "S.S. Rajamouli",
          "cast": "Prabhas, Rana Daggubati, Anushka Shetty, Tamannaah Bhatia",
          "worldwidegross": "1807cr\n\nWorldwide Share",
          "imdbRating": "8.2"
        },
        {
          "id": "top_grossing_telugu_000102",
          "name": "Baahubali: The Beginning",
          "synopsis": "In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples.",
          "releaseYear": "2015",
          "moviegenre": "Action, Drama",
          "director": "S.S. Rajamouli",
          "cast": "Prabhas, Rana Daggubati, Ramya Krishnan, Sathyaraj",
          "worldwidegross": "602cr\n\nWorldwide Share",
          "imdbRating": "8"
        },
        {
          "id": "top_grossing_telugu_000103",
          "name": "Saaho",
          "synopsis": "An undercover cop becomes embroiled in a battle with warring criminals who want to acquire a \"black box,\" their ultimate key to a treasure.",
          "releaseYear": "2019",
          "moviegenre": "Action, Thriller",
          "director": "Sujeeth",
          "cast": "Prabhas, Shraddha Kapoor, Jackie Shroff, Neil Nitin Mukesh",
          "worldwidegross": "420.6cr\n\nWorldwide Share",
          "imdbRating": "5.2"
        },
        {
          "id": "top_grossing_telugu_000104",
          "name": "Ala Vaikunthapurramuloo",
          "synopsis": "Fate plays a vital role in connecting the life of Bantu, a son who seeks validation from his cold-hearted father with the life of Raj, whose millionaire father wishes that he was more assertive.",
          "releaseYear": "2020",
          "moviegenre": "Action, Comedy, Drama",
          "director": "Trivikram Srinivas",
          "cast": "Allu Arjun, Pooja Hegde, Tabu, Jayaram",
          "worldwidegross": "274.4cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000105",
          "name": "Sye Raa Narasimha Reddy",
          "synopsis": "A historical action epic inspired by the life of Uyyalawada Narasimha Reddy, who revolted against the atrocities of East India Company 10 years before the Sepoy Mutiny.",
          "releaseYear": "2019",
          "moviegenre": "Action, Adventure, Drama",
          "director": "Surender Reddy",
          "cast": "Chiranjeevi, Amitabh Bachchan, Sudeep, Vijay Sethupathi",
          "worldwidegross": "248cr\n\nWorldwide Share",
          "imdbRating": "7.4"
        },
        {
          "id": "top_grossing_telugu_000106",
          "name": "Sarileru Neekevvaru",
          "synopsis": "A tough army major is deployed to Kurnool on a mission to keep the country safe from external threats.",
          "releaseYear": "2020",
          "moviegenre": "Action, Comedy, Drama",
          "director": "Anil Ravipudi",
          "cast": "Mahesh Babu, Rashmika Mandanna, Vijayshanti, Rajendra Prasad",
          "worldwidegross": "237.1cr\n\nWorldwide Share",
          "imdbRating": "6"
        },
        {
          "id": "top_grossing_telugu_000107",
          "name": "Rangasthalam 1985",
          "synopsis": "Chitti Babu begins to suspect his elder brother's life is in danger after they team up to lock horns with their village president and overthrow his unlawful 30 year old regime.",
          "releaseYear": "2018",
          "moviegenre": "Action, Drama",
          "director": "Sukumar",
          "cast": "Ram Charan, Samantha Ruth Prabhu, Aadhi, Jagapathi Babu",
          "worldwidegross": "213.4cr\n\nWorldwide Share",
          "imdbRating": "8.4"
        },
        {
          "id": "top_grossing_telugu_000108",
          "name": "Maharshi",
          "synopsis": "Rishi, a millionaire businessman, returns to his homeland, where he becomes the champion of poor and downtrodden farmers.",
          "releaseYear": "2019",
          "moviegenre": "Action, Drama",
          "director": "Vamshi Paidipally",
          "cast": "Mahesh Babu, Allari Naresh, Pooja Hegde, Jagapathi Babu",
          "worldwidegross": "184.6cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000109",
          "name": "Bharath Ane Nenu",
          "synopsis": "Bharat, an young graduate, becomes the C.M of Andhra Pradesh (pre-div) after his father demise without any political knowledge, faces challenges in the process of reform the society.",
          "releaseYear": "2018",
          "moviegenre": "Action, Drama",
          "director": "Koratala Siva",
          "cast": "Mahesh Babu, Kiara Advani, Prakash Raj, Sarath Kumar",
          "worldwidegross": "178.1cr\n\nWorldwide Share",
          "imdbRating": "7.7"
        },
        {
          "id": "top_grossing_telugu_000110",
          "name": "Khaidi No. 150",
          "synopsis": "A convict who plans to escape the country unexpectedly switches his place with a good Samaritan who fights for the rights of poor farmers.",
          "releaseYear": "2017",
          "moviegenre": "Action, Drama, Romance",
          "director": "V.V. Vinayak",
          "cast": "Chiranjeevi, Kajal Aggarwal, Tarun Arora, Ali",
          "worldwidegross": "165.5cr\n\nWorldwide Share",
          "imdbRating": "6"
        },
        {
          "id": "top_grossing_telugu_000111",
          "name": "Aravindha Sametha",
          "synopsis": "A young scion of a powerful family with a long history of violence decides to put an end to the bloodshed which leads him to a path of self discovery.",
          "releaseYear": "2018",
          "moviegenre": "Action, Drama",
          "director": "Trivikram Srinivas",
          "cast": "N.T. Rama Rao Jr., Pooja Hegde, Jagapathi Babu, Naveen Chandra",
          "worldwidegross": "155cr\n\nWorldwide Share",
          "imdbRating": "7.6"
        },
        {
          "id": "top_grossing_telugu_000112",
          "name": "Srimanthudu",
          "synopsis": "Harsha, a multi-millionaire who has everything, still feels that there is something missing in his life. In an attempt to fill the void, he adopts a village to bring change in the people.",
          "releaseYear": "2015",
          "moviegenre": "Action, Drama",
          "director": "Koratala Siva",
          "cast": "Mahesh Babu, Shruti Haasan, Jagapathi Babu, Rajendra Prasad",
          "worldwidegross": "151cr\n\nWorldwide Share",
          "imdbRating": "7.6"
        },
        {
          "id": "top_grossing_telugu_000113",
          "name": "F2: Fun and Frustration",
          "synopsis": "After Venky, Varun also gets married thinking he can keep the wife in control but both of them get frustrated with the marital life which generates fun.",
          "releaseYear": "2019",
          "moviegenre": "Comedy",
          "director": "Anil Ravipudi",
          "cast": "Tamannaah Bhatia, Prakash Raj, Nassar, Varun Tej",
          "worldwidegross": "140.5cr\n\nWorldwide Share",
          "imdbRating": "6.2"
        },
        {
          "id": "top_grossing_telugu_000114",
          "name": "Janatha Garage",
          "synopsis": "An environmental activist comes to Hyderabad to attend a seminar, where an unexpected encounter with a man who runs an organization for the oppressed, changes his purpose in life.",
          "releaseYear": "2016",
          "moviegenre": "Action, Crime, Drama",
          "director": "Koratala Siva",
          "cast": "Mohanlal, N.T. Rama Rao Jr., Samantha Ruth Prabhu, Nithya Menen",
          "worldwidegross": "138.5cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000115",
          "name": "Vakeel Saab",
          "synopsis": "Three girls find themselves accused of attempt to murder after escaping molestation. Their only hope is an alcoholic lawyer who agrees to take up the case.",
          "releaseYear": "2021",
          "moviegenre": "Action, Crime, Drama",
          "director": "Venu Sriram",
          "cast": "Pawan Kalyan, Nivetha Thomas, Anjali, Ananya Nagalla",
          "worldwidegross": "137.2cr\n\nWorldwide Share",
          "imdbRating": "7.8"
        },
        {
          "id": "top_grossing_telugu_000116",
          "name": "Atharintiki Daaredi",
          "synopsis": "The scion of a powerful family is tasked with retrieving an estranged family member.",
          "releaseYear": "2013",
          "moviegenre": "Action, Comedy, Drama",
          "director": "Trivikram Srinivas",
          "cast": "Pawan Kalyan, Samantha Ruth Prabhu, Pranitha, Boman Irani",
          "worldwidegross": "135.6cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000117",
          "name": "Sarrainodu",
          "synopsis": "An intense battle breaks out between an evil son of a politician and an ex army man who can't tolerate injustice.",
          "releaseYear": "2016",
          "moviegenre": "Action, Drama",
          "director": "Boyapati Srinu",
          "cast": "Allu Arjun, Aadhi, Rakul Preet Singh, Catherine Tresa",
          "worldwidegross": "131.2cr\n\nWorldwide Share",
          "imdbRating": "6.6"
        },
        {
          "id": "top_grossing_telugu_000118",
          "name": "Jai Lava Kusa",
          "synopsis": "Sidelined at a very young age due to stammering, the eldest of identical triplets develops hatred for his younger brothers and creates havoc in their lives as they all reunite as adults.",
          "releaseYear": "2017",
          "moviegenre": "Action, Drama, Thriller",
          "director": "K.S. Ravindra",
          "cast": "N.T. Rama Rao Jr., Raashi Khanna, Nivetha Thomas, Ronit Roy",
          "worldwidegross": "130.4cr\n\nWorldwide Share",
          "imdbRating": "7"
        },
        {
          "id": "top_grossing_telugu_000119",
          "name": "Magadheera",
          "synopsis": "A warrior gets reincarnated 400 years later, after trying to save the princess and the kingdom, who also dies along with him. He then sets back again to fight against all odds and win back his love.",
          "releaseYear": "2009",
          "moviegenre": "Action, Drama, Fantasy",
          "director": "S.S. Rajamouli",
          "cast": "Ram Charan, Kajal Aggarwal, Dev Gill, Srihari",
          "worldwidegross": "129cr\n\nWorldwide Share",
          "imdbRating": "7.7"
        },
        {
          "id": "top_grossing_telugu_000120",
          "name": "Geetha Govindam",
          "synopsis": "An innocent young lecturer is misunderstood as a pervert and despised by a woman who co-incidentally turns out to be the younger sister of his brother-in-law. Eventually differences subside and love blooms between them.",
          "releaseYear": "2018",
          "moviegenre": "Drama, Romance",
          "director": "Parasuram",
          "cast": "Vijay Deverakonda, Rashmika Mandanna, Subbaraju, Mouryaani",
          "worldwidegross": "126cr\n\nWorldwide Share",
          "imdbRating": "7.7"
        },
        {
          "id": "top_grossing_telugu_000121",
          "name": "Spyder",
          "synopsis": "An intelligence officer attempts to save the city from a psychotic serial killer who kills people just to hear their loved ones cry.",
          "releaseYear": "2017",
          "moviegenre": "Action, Crime, Thriller",
          "director": "A.R. Murugadoss",
          "cast": "Mahesh Babu, Rakul Preet Singh, S.J. Suryah, Bharath Srinivasan",
          "worldwidegross": "121.3cr\n\nWorldwide Share",
          "imdbRating": "6.6"
        },
        {
          "id": "top_grossing_telugu_000122",
          "name": "Duvvada Jagannadham",
          "synopsis": "Trained by a high profile cop, an encounter specialist masquerading as a Brahmin priest takes on a real estate crime organization after losing his uncle.",
          "releaseYear": "2017",
          "moviegenre": "Action, Comedy, Crime",
          "director": "Harish Shankar",
          "cast": "Allu Arjun, Pooja Hegde, Rao Ramesh, Murli Sharma",
          "worldwidegross": "119cr\n\nWorldwide Share",
          "imdbRating": "5.8"
        },
        {
          "id": "top_grossing_telugu_000123",
          "name": "Gabbar Singh",
          "synopsis": "Inspired by a movie character in Sholay, Venkataratnam, a policeman, calls himself Gabbar Singh. He's postedin a village where an area thug wants to join politics and also lures his stepbrother to hitch him.",
          "releaseYear": "2012",
          "moviegenre": "Action, Comedy, Crime",
          "director": "Harish Shankar",
          "cast": "Pawan Kalyan, Shruti Haasan, Abhimanyu Singh, Kota Srinivasa Rao",
          "worldwidegross": "108cr\n\nWorldwide Share",
          "imdbRating": "7.1"
        },
        {
          "id": "top_grossing_telugu_000124",
          "name": "Race Gurram",
          "synopsis": "Two brothers have two different approaches to life. While one brother follows rules and regulations, the other does things his own way.",
          "releaseYear": "2014",
          "moviegenre": "Action, Comedy",
          "director": "Surender Reddy",
          "cast": "Allu Arjun, Shruti Haasan, Shaam, Ravi Kishan",
          "worldwidegross": "105cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000125",
          "name": "Eega",
          "synopsis": "A murdered man is reincarnated as a housefly and seeks to avenge his death.",
          "releaseYear": "2012",
          "moviegenre": "Action, Comedy, Fantasy",
          "director": "S.S. Rajamouli",
          "cast": "Sudeep, Nani, Samantha Ruth Prabhu, Hamsa Nandini",
          "worldwidegross": "102.8cr\n\nWorldwide Share",
          "imdbRating": "7.7"
        },
        {
          "id": "top_grossing_telugu_000126",
          "name": "Dookudu",
          "synopsis": "Ajay, (Mahesh Babu) an undercover cop, is assigned to catch a dangerous mafia don with whom he has a personal score to settle.",
          "releaseYear": "2011",
          "moviegenre": "Action, Comedy",
          "director": "Sreenu Vaitla",
          "cast": "Mahesh Babu, Samantha Ruth Prabhu, Sonu Sood, Kota Srinivasa Rao",
          "worldwidegross": "101cr\n\nWorldwide Share",
          "imdbRating": "7.4"
        },
        {
          "id": "top_grossing_telugu_000127",
          "name": "Katamarayudu",
          "synopsis": "A man with a violent streak is trying to reform but gets pushed into a situation where he has to take action.",
          "releaseYear": "2017",
          "moviegenre": "Action, Comedy",
          "director": "Kishore Kumar Pardasani",
          "cast": "Pawan Kalyan, Shruti Haasan, Ajay, Rao Ramesh",
          "worldwidegross": "100.7cr\n\nWorldwide Share",
          "imdbRating": "5.7"
        },
        {
          "id": "top_grossing_telugu_000128",
          "name": "Vinaya Vidheya Rama",
          "synopsis": "When the happiness of his family is held to ransom by a violent crime lord, Ram sets out on a quest to destroy his nemesis and his criminal empire.",
          "releaseYear": "2019",
          "moviegenre": "Action",
          "director": "Boyapati Srinu",
          "cast": "Ram Charan, Kiara Advani, Aadhithya, Aadhya Aarnav",
          "worldwidegross": "99.4cr\n\nWorldwide Share",
          "imdbRating": "3.3"
        },
        {
          "id": "top_grossing_telugu_000129",
          "name": "Dhruva",
          "synopsis": "A committed police officer is on a very dangerous mission to destroy the most corrupt person in the country, Siddharth Abhimanyu.",
          "releaseYear": "2016",
          "moviegenre": "Action, Crime, Thriller",
          "director": "Surender Reddy",
          "cast": "Ram Charan, Arvind Swamy, Rakul Preet Singh, Olga Andrievskaya",
          "worldwidegross": "97.5cr\n\nWorldwide Share",
          "imdbRating": "7.8"
        },
        {
          "id": "top_grossing_telugu_000130",
          "name": "Oopiri",
          "synopsis": "Impressed by his carefree attitude, Vikram, a quadriplegic multi-billionaire, hires a convict out on parole as his caretaker. What follows is a string of life lessons they learn from each other.",
          "releaseYear": "2016",
          "moviegenre": "Comedy, Drama",
          "director": "Vamshi Paidipally",
          "cast": "Nagarjuna Akkineni, Karthi, Tamannaah Bhatia, Prakash Raj",
          "worldwidegross": "96.9cr\n\nWorldwide Share",
          "imdbRating": "8"
        },
        {
          "id": "top_grossing_telugu_000131",
          "name": "Uppena",
          "synopsis": "The son of a fishing community falls for a village head's daughter, but they face violent opposition from the girl's doggedly old-fashioned father.",
          "releaseYear": "2021",
          "moviegenre": "Action, Drama, Romance",
          "director": "Buchi Babu Sana",
          "cast": "Panja Vaisshnav Tej, Krithi Shetty, Vijay Sethupathi, Gayatri Jayaraman",
          "worldwidegross": "96.1cr\n\nWorldwide Share",
          "imdbRating": "6.8"
        },
        {
          "id": "top_grossing_telugu_000132",
          "name": "Agnathavasi - Prince in Exile",
          "synopsis": "An exiled heir to billionaire, returns after his father was murdered, as a regular employee to find out the killers and make things right in his company.",
          "releaseYear": "2018",
          "moviegenre": "Action, Drama",
          "director": "Trivikram Srinivas",
          "cast": "Pawan Kalyan, Keerthy Suresh, Anu Emmanuel, Aadhi",
          "worldwidegross": "93.1cr\n\nWorldwide Share",
          "imdbRating": "4.5"
        },
        {
          "id": "top_grossing_telugu_000133",
          "name": "Naa Peru Surya Naa Illu India",
          "synopsis": "Following two violent incidents at a club and a police station, a short tempered soldier is challenged to give up anger if he wants to fulfill his dream of serving at the borders.",
          "releaseYear": "2018",
          "moviegenre": "Action, Drama",
          "director": "Vakkantham Vamsi",
          "cast": "Allu Arjun, Sam Nagar, Anu Emmanuel, Arjun Sarja",
          "worldwidegross": "92.6cr\n\nWorldwide Share",
          "imdbRating": "6.8"
        },
        {
          "id": "top_grossing_telugu_000134",
          "name": "Nenjamellam Pala Vannam",
          "synopsis": "An exuberant and evocative family drama, that primarily revolves around the close bond between two brothers with radically different personalities, highlighting the complex process of choosing an ideal life partner for each of them.",
          "releaseYear": "2013",
          "moviegenre": "Comedy, Drama",
          "director": "Srikanth Addala",
          "cast": "Venkatesh Daggubati, Mahesh Babu, Anjali, Samantha Ruth Prabhu",
          "worldwidegross": "92.1cr\n\nWorldwide Share",
          "imdbRating": "7.5"
        },
        {
          "id": "top_grossing_telugu_000135",
          "name": "Fidaa",
          "synopsis": "Varun and Bhanu, both from different worlds, face challenges in their relationship.",
          "releaseYear": "2017",
          "moviegenre": "Comedy, Drama, Romance",
          "director": "Sekhar Kammula",
          "cast": "Sai Pallavi, Varun Tej, Sarah Uriarte Berry, Harshvardhan Rane",
          "worldwidegross": "91.8cr\n\nWorldwide Share",
          "imdbRating": "7.5"
        },
        {
          "id": "top_grossing_telugu_000136",
          "name": "S/O Satyamurthy",
          "synopsis": "A rich businessman's son faces multiple challenges after he becomes the sole breadwinner of his family.",
          "releaseYear": "2015",
          "moviegenre": "Action, Drama",
          "director": "Trivikram Srinivas",
          "cast": "Allu Arjun, Samantha Ruth Prabhu, Adah Sharma, Nithya Menen",
          "worldwidegross": "91.3cr\n\nWorldwide Share",
          "imdbRating": "7"
        },
        {
          "id": "top_grossing_telugu_000137",
          "name": "Nannaku Prematho",
          "synopsis": "An intelligent son of a former entrepreneur takes revenge on a powerful and rich businessman who is as smart as he is.",
          "releaseYear": "2016",
          "moviegenre": "Action, Drama, Thriller",
          "director": "Sukumar",
          "cast": "N.T. Rama Rao Jr., Rakul Preet Singh, Jagapathi Babu, Rajendra Prasad",
          "worldwidegross": "89.8cr\n\nWorldwide Share",
          "imdbRating": "7.6"
        },
        {
          "id": "top_grossing_telugu_000138",
          "name": "Sardaar Gabbar Singh",
          "synopsis": "A kingdom called Rathanpur was taken ruthlessly by a feudal lord named Bhairav Singh. The princess of that empire was in a hopeless situation until a maverick cop named Sardaar Gabbar Singh came along.",
          "releaseYear": "2016",
          "moviegenre": "Action, Comedy, Crime",
          "director": "K.S. Ravindra",
          "cast": "Kajal Aggarwal, Pawan Kalyan, Sharad Kelkar, Raai Laxmi",
          "worldwidegross": "86cr\n\nWorldwide Share",
          "imdbRating": "4.8"
        },
        {
          "id": "top_grossing_telugu_000139",
          "name": "Mahanati",
          "synopsis": "Biography of Savitri, an actress from South India movie industry, who ruled the industry for two decades during 50s and 60s.",
          "releaseYear": "2018",
          "moviegenre": "Biography, Drama",
          "director": "Nag Ashwin",
          "cast": "Keerthy Suresh, Dulquer Salmaan, Samantha Ruth Prabhu, Vijay Deverakonda",
          "worldwidegross": "85.1cr\n\nWorldwide Share",
          "imdbRating": "8.5"
        },
        {
          "id": "top_grossing_telugu_000140",
          "name": "Rudhramadevi",
          "synopsis": "Queen Rudrama Devi's reign in southern India during the 13th century is herein recounted.",
          "releaseYear": "2015",
          "moviegenre": "Action, Biography, Drama",
          "director": "Gunasekhar",
          "cast": "Anushka Shetty, Allu Arjun, Rana Daggubati, Vikramjeet Virk",
          "worldwidegross": "85cr\n\nWorldwide Share",
          "imdbRating": "5.8"
        },
        {
          "id": "top_grossing_telugu_000141",
          "name": "Soggade Chinni Nayana",
          "synopsis": "To keep her late husband's son and his wife from seeking a divorce, a widow enlists the help of her husband's spirit.",
          "releaseYear": "2016",
          "moviegenre": "Comedy, Drama",
          "director": "Kalyan Krishna",
          "cast": "Nagarjuna Akkineni, Ramya Krishnan, Lavanya Tripathi, Banerjee",
          "worldwidegross": "84.4cr\n\nWorldwide Share",
          "imdbRating": "6.4"
        },
        {
          "id": "top_grossing_telugu_000142",
          "name": "Mirchi",
          "synopsis": "A man returns to his country in order, ostensibly, to reform his girlfriend's violent family, but he seems to have a strange connection and a rather dark past.",
          "releaseYear": "2013",
          "moviegenre": "Action, Drama",
          "director": "Koratala Siva",
          "cast": "Prabhas, Anushka Shetty, Richa Langella, Sathyaraj",
          "worldwidegross": "84.3cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000143",
          "name": "Yevadu",
          "synopsis": "A young man receives a life-saving face transplant after he is critically injured and his girlfriend murdered in a vicious attack. Unrecognisable to his enemies, he sets out for revenge.",
          "releaseYear": "2014",
          "moviegenre": "Action, Thriller",
          "director": "Vamshi Paidipally",
          "cast": "Ram Charan, Allu Arjun, Shruti Haasan, Kajal Aggarwal",
          "worldwidegross": "83.5cr\n\nWorldwide Share",
          "imdbRating": "5.7"
        },
        {
          "id": "top_grossing_telugu_000144",
          "name": "Naayak",
          "synopsis": "A young man and his lookalike team up to fight injustice and settle their personal scores with the evildoers.",
          "releaseYear": "2013",
          "moviegenre": "Action, Drama",
          "director": "V.V. Vinayak",
          "cast": "Ram Charan, Kajal Aggarwal, Amala Paul, Anandhi",
          "worldwidegross": "82.7cr\n\nWorldwide Share",
          "imdbRating": "5.6"
        },
        {
          "id": "top_grossing_telugu_000145",
          "name": "A Aa",
          "synopsis": "Anand and Anasuya meet each other on a train ride. The two eventually fall in love and have to fight for their relationship.",
          "releaseYear": "2016",
          "moviegenre": "Comedy, Drama, Romance",
          "director": "Trivikram Srinivas",
          "cast": "Nithiin, Samantha Ruth Prabhu, Anupama Parameswaran, Nadia Moidu",
          "worldwidegross": "81.5cr\n\nWorldwide Share",
          "imdbRating": "6.8"
        },
        {
          "id": "top_grossing_telugu_000146",
          "name": "Ra Cha",
          "synopsis": "A betting teenager involves in a larger bet than he imagined.",
          "releaseYear": "2012",
          "moviegenre": "Action",
          "director": "Sampath Nandi",
          "cast": "Ram Charan, Tamannaah Bhatia, Ajmal Ameer, Kota Srinivasa Rao",
          "worldwidegross": "81cr\n\nWorldwide Share",
          "imdbRating": "4.4"
        },
        {
          "id": "top_grossing_telugu_000147",
          "name": "Gautamiputra Satakarni",
          "synopsis": "This movie chronicles the life of a South Indian ruler of the Satavahana Empire in South India in the 2nd century CE.",
          "releaseYear": "2017",
          "moviegenre": "Action, History",
          "director": "Radha Krishna Jagarlamudi",
          "cast": "Nandamuri Balakrishna, Hema Malini, Shriya Saran, Kabir Bedi",
          "worldwidegross": "80.7cr\n\nWorldwide Share",
          "imdbRating": "6.4"
        },
        {
          "id": "top_grossing_telugu_000148",
          "name": "Baadshah",
          "synopsis": "Rama Rao fails to get a job with the police force due to his father's connections with a gangster. But when his brother is killed by the gangster, Rama Rao becomes Baadshah to oppose him.",
          "releaseYear": "2013",
          "moviegenre": "Action, Comedy",
          "director": "Sreenu Vaitla",
          "cast": "Mahesh Babu, Siddharth, Kajal Aggarwal, N.T. Rama Rao Jr.",
          "worldwidegross": "80.6cr\n\nWorldwide Share",
          "imdbRating": "6.4"
        },
        {
          "id": "top_grossing_telugu_000149",
          "name": "Krack",
          "synopsis": "Krack is an action film which follows Veera Shankar, a hot headed police sergeant, who forms a vicious rivalry with notorious crime figure, Katari Krishna.",
          "releaseYear": "2021",
          "moviegenre": "Action, Crime, Thriller",
          "director": "Gopichand Malineni",
          "cast": "Ravi Teja, Shruti Haasan, Samuthirakani, Varalaxmi Sarathkumar",
          "worldwidegross": "76.1cr\n\nWorldwide Share",
          "imdbRating": "7.2"
        },
        {
          "id": "top_grossing_telugu_000150",
          "name": "Temper",
          "synopsis": "Daya, a corrupt police officer, finds his life changing when he takes on a case of gang rape.",
          "releaseYear": "2015",
          "moviegenre": "Action, Crime, Drama",
          "director": "Puri Jagannadh",
          "cast": "N.T. Rama Rao Jr., Kajal Aggarwal, Prakash Raj, Kota Srinivasa Rao",
          "worldwidegross": "74.7cr\n\nWorldwide Share",
          "imdbRating": "7.4"
        },
        {
          "id": "top_grossing_telugu_000151",
          "name": "Arundhati",
          "synopsis": "A brave queen battles an evil mystic. Three generations later, he comes back to haunt the queen's descendants.",
          "releaseYear": "2009",
          "moviegenre": "Horror, Mystery, Thriller",
          "director": "Kodi Ramakrishna",
          "cast": "Anushka Shetty, Sonu Sood, Divya Nagesh, Aachi Manorama",
          "worldwidegross": "73.5cr\n\nWorldwide Share",
          "imdbRating": "7.4"
        },
        {
          "id": "top_grossing_telugu_000152",
          "name": "Business Man",
          "synopsis": "Surya arrives in Mumbai to revive the mafia and ends up making enemies who threaten his life.",
          "releaseYear": "2012",
          "moviegenre": "Action, Crime",
          "director": "Puri Jagannadh",
          "cast": "Mahesh Babu, Kajal Aggarwal, Prakash Raj, Ayesha Shiva",
          "worldwidegross": "73.4cr\n\nWorldwide Share",
          "imdbRating": "7.2"
        },
        {
          "id": "top_grossing_telugu_000153",
          "name": "Govindudu Andari Vaadele",
          "synopsis": "A man returns to India to find his family on the brink of a rift. He must push past his tendency to take everything lightly and work to heal his clan.",
          "releaseYear": "2014",
          "moviegenre": "Action, Drama",
          "director": "Krishna Vamsi",
          "cast": "Ram Charan, Kajal Aggarwal, Srikanth, Kamalinee Mukherjee",
          "worldwidegross": "72.6cr\n\nWorldwide Share",
          "imdbRating": "5.7"
        },
        {
          "id": "top_grossing_telugu_000154",
          "name": "MCA Middle Class Abbayi",
          "synopsis": "A youngster tries to protect his sister-in-law, a transport official, from a dreaded goon who runs an illegal road transport business.",
          "releaseYear": "2017",
          "moviegenre": "Action, Comedy",
          "director": "Venu Sriram",
          "cast": "Nani, Sai Pallavi, Bhoomika Chawla, Rajeev Kanakala",
          "worldwidegross": "72.6cr\n\nWorldwide Share",
          "imdbRating": "6"
        },
        {
          "id": "top_grossing_telugu_000155",
          "name": "Gopala Gopala",
          "synopsis": "An atheist sues god after losing his shop in an earthquake.",
          "releaseYear": "2015",
          "moviegenre": "Comedy, Drama, Fantasy",
          "director": "Kishore Kumar Pardasani",
          "cast": "Venkatesh Daggubati, Pawan Kalyan, Shriya Saran, Mithun Chakraborty",
          "worldwidegross": "71.8cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000156",
          "name": "Jathi Ratnalu",
          "synopsis": "The plot revolves around the three prisoners. They get released and plan for a happy life outside. Things take a new turn and bring in a twist. Can they find happiness and love now?",
          "releaseYear": "2021",
          "moviegenre": "Comedy",
          "director": "Anudeep K.V.",
          "cast": "Naveen Polishetty, Rahul Ramakrishna, Priyadarshi, Faria Abdullah",
          "worldwidegross": "71.2cr\n\nWorldwide Share",
          "imdbRating": "7.6"
        },
        {
          "id": "top_grossing_telugu_000157",
          "name": "Legend",
          "synopsis": "Krishna, Who Lives In Dubai, Falls In Love With Sneha. He Comes To India To Seek The Blessings Of His Grandmother, Unaware That Don Jeetendra's Gang Is Seeking Revenge.",
          "releaseYear": "II (2014)",
          "moviegenre": "Action, Drama",
          "director": "Boyapati Srinu",
          "cast": "Nandamuri Balakrishna, Jagapathi Babu, Radhika Apte, Sonal Chauhan",
          "worldwidegross": "70.2cr\n\nWorldwide Share",
          "imdbRating": "6.3"
        },
        {
          "id": "top_grossing_telugu_000158",
          "name": "Julayi",
          "synopsis": "After helping the police foil a violent heist, a sharp minded young man must evade the criminal mastermind whose plans he has thwarted.",
          "releaseYear": "2012",
          "moviegenre": "Action, Comedy, Crime",
          "director": "Trivikram Srinivas",
          "cast": "Allu Arjun, Ileana D'Cruz, Rajendra Prasad, Sonu Sood",
          "worldwidegross": "70cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000159",
          "name": "Bruce Lee - The Fighter",
          "synopsis": "A stuntman is mistaken for a police officer by an idealistic woman and begins fighting crime on behalf of the police.",
          "releaseYear": "2015",
          "moviegenre": "Action, Comedy",
          "director": "Sreenu Vaitla",
          "cast": "Ram Charan, Rakul Preet Singh, Ali, Tanikella Bharani",
          "worldwidegross": "68.6cr\n\nWorldwide Share",
          "imdbRating": "5.5"
        },
        {
          "id": "top_grossing_telugu_000160",
          "name": "Bhaagamathie",
          "synopsis": "IAS officer Chanchala Reddy is imprisoned in a haunted house, while she is interrogated by law enforcers investigating a politician they suspect of corruption.",
          "releaseYear": "2018",
          "moviegenre": "Action, Horror, Thriller",
          "director": "Ashok G.",
          "cast": "Anushka Shetty, Unni Mukundan, Jayaram, Surekha Vani",
          "worldwidegross": "66.8cr\n\nWorldwide Share",
          "imdbRating": "7"
        },
        {
          "id": "top_grossing_telugu_000161",
          "name": "iSmart Shankar",
          "synopsis": "A contract killer escapes after murdering a politician and must help the cops find a murderer after a slain officer's memories are transferred to his brain.",
          "releaseYear": "2019",
          "moviegenre": "Action, Crime, Sci-Fi",
          "director": "Directors: Puri Jagannadh, A. Sreedhar",
          "cast": "Ram Pothineni, Satyadev Kancharana, Nabha Natesh, Nidhhi Agerwal",
          "worldwidegross": "66.7cr\n\nWorldwide Share",
          "imdbRating": "5.6"
        },
        {
          "id": "top_grossing_telugu_000162",
          "name": "Pokiri",
          "synopsis": "A local goon's killer instincts earn him his girlfriend's disapproval, a corrupt cop's enmity and a wanted don's attention.",
          "releaseYear": "2006",
          "moviegenre": "Action, Crime, Thriller",
          "director": "Puri Jagannadh",
          "cast": "Mahesh Babu, Ileana D'Cruz, Prakash Raj, Nassar",
          "worldwidegross": "66.1cr\n\nWorldwide Share",
          "imdbRating": "7.9"
        },
        {
          "id": "top_grossing_telugu_000163",
          "name": "Majili",
          "synopsis": "After being abandoned by his lover, Anshu, Poorna takes to alcohol and is forced to marry his neighbour, Sravani. However, he soon discovers her unrequited love for him and falls for her.",
          "releaseYear": "2019",
          "moviegenre": "Drama, Romance",
          "director": "Shiva Nirvana",
          "cast": "Samantha Ruth Prabhu, Naga Chaitanya Akkineni, Atul Kulkarni, Divyansha Kaushik",
          "worldwidegross": "66cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000164",
          "name": "Aagadu",
          "synopsis": "An encounter specialist is transferred as CI to a village which is ruled by a local gangster",
          "releaseYear": "2014",
          "moviegenre": "Action, Comedy",
          "director": "Sreenu Vaitla",
          "cast": "Tamannaah Bhatia, Shruti Haasan, Mahesh Babu, Nassar",
          "worldwidegross": "65.1cr\n\nWorldwide Share",
          "imdbRating": "5.4"
        },
        {
          "id": "top_grossing_telugu_000165",
          "name": "Manam",
          "synopsis": "Through reincarnation, family members are able to cross generations and meddle in each others' lives.",
          "releaseYear": "I (2014)",
          "moviegenre": "Comedy, Drama, Fantasy",
          "director": "Vikram K. Kumar",
          "cast": "Akkineni Nageshwara Rao, Nagarjuna Akkineni, Naga Chaitanya Akkineni, Samantha Ruth Prabhu",
          "worldwidegross": "64.3cr\n\nWorldwide Share",
          "imdbRating": "8"
        },
        {
          "id": "top_grossing_telugu_000166",
          "name": "Anirudh",
          "synopsis": "To consolidate his position in the family, a man tries to arrange a marriage for his daughter, but the suitable boy he has in mind is already in love with another.",
          "releaseYear": "2016",
          "moviegenre": "Action, Drama, Romance",
          "director": "Srikanth Addala",
          "cast": "Mahesh Babu, Kajal Aggarwal, Samantha Ruth Prabhu, Pranitha",
          "worldwidegross": "63.5cr\n\nWorldwide Share",
          "imdbRating": "4.3"
        },
        {
          "id": "top_grossing_telugu_000167",
          "name": "The Ghazi Attack",
          "synopsis": "A Pakistani submarine, Ghazi plans to secretly attack Vizag port. For doing so, it has to get past Indian submarine S21.",
          "releaseYear": "2017",
          "moviegenre": "Action, Thriller, War",
          "director": "Sankalp Reddy",
          "cast": "Rana Daggubati, Kay Kay Menon, Atul Kulkarni, Om Puri",
          "worldwidegross": "63cr\n\nWorldwide Share",
          "imdbRating": "7.6"
        },
        {
          "id": "top_grossing_telugu_000168",
          "name": "Venky Mama",
          "synopsis": "A story of nephew and a son which revolves around their emotions and village drama and army based story.",
          "releaseYear": "2019",
          "moviegenre": "Action, Comedy, Drama",
          "director": "K.S. Ravindra",
          "cast": "Raashi Khanna, Naga Chaitanya Akkineni, Prakash Raj, Payal Rajput",
          "worldwidegross": "61.8cr\n\nWorldwide Share",
          "imdbRating": "5.5"
        },
        {
          "id": "top_grossing_telugu_000169",
          "name": "Love Story",
          "synopsis": "A love story of a boy and girl who move to the city from their village to pursue their dreams.",
          "releaseYear": "2021",
          "moviegenre": "Romance",
          "director": "Sekhar Kammula",
          "cast": "Naga Chaitanya Akkineni, Sai Pallavi, Devayani, Sachin Yadav Iamsyrs",
          "worldwidegross": "60.6cr (still running)\n\nWorldwide Share",
          "imdbRating": "7.8"
        },
        {
          "id": "top_grossing_telugu_000170",
          "name": "Cameraman Gangatho Rambabu",
          "synopsis": "A fast-paced socially relevant political drama that revolves around the struggles of an ordinary citizen against crime and political corruption.",
          "releaseYear": "2012",
          "moviegenre": "Action, Drama",
          "director": "Puri Jagannadh",
          "cast": "Pawan Kalyan, Tamannaah Bhatia, Prakash Raj, Ali",
          "worldwidegross": "60.6cr\n\nWorldwide Share",
          "imdbRating": "5.7"
        },
        {
          "id": "top_grossing_telugu_000171",
          "name": "Prati Roju Pandaage",
          "synopsis": "With only a few weeks left to live, an aging grandfather is visited by his grandson who wishes to fulfill his desires.",
          "releaseYear": "2019",
          "moviegenre": "Drama, Family",
          "director": "Maruthi Dasari",
          "cast": "Mahesh Achanta, Ajay, Bhadram, Gayatri Bhargavi",
          "worldwidegross": "60.2cr\n\nWorldwide Share",
          "imdbRating": "6.3"
        },
        {
          "id": "top_grossing_telugu_000172",
          "name": "Dhammu",
          "synopsis": "An orphan gets adopted by a rich and powerful family looking for a heir. But the family has a dark violent past due to dispute with a rival family. What will he do when the fate of his village depends on him?",
          "releaseYear": "2012",
          "moviegenre": "Action, Drama",
          "director": "Boyapati Srinu",
          "cast": "N.T. Rama Rao Jr., Trisha Krishnan, Karthika Nair, Nassar",
          "worldwidegross": "60.1cr\n\nWorldwide Share",
          "imdbRating": "5.1"
        },
        {
          "id": "top_grossing_telugu_000173",
          "name": "Nenu Local",
          "synopsis": "A happy-go-lucky man accidentally falls in love with a woman whose father despises him. To further complicate matters, his lover has another suitor, who is deemed more worthy of her.",
          "releaseYear": "2017",
          "moviegenre": "Action, Comedy, Romance",
          "director": "Trinadha Rao Nakkina",
          "cast": "Nani, Keerthy Suresh, Naveen Chandra, Sachin Khedekar",
          "worldwidegross": "60cr\n\nWorldwide Share",
          "imdbRating": "6.5"
        },
        {
          "id": "top_grossing_telugu_000174",
          "name": "Ninnu Kori",
          "synopsis": "Two lovers, Pallavi and Uma get separated by circumstances, but reconnect years later, when Pallavi is happily married to someone else.",
          "releaseYear": "2017",
          "moviegenre": "Comedy, Romance",
          "director": "Shiva Nirvana",
          "cast": "Nani, Nivetha Thomas, Aadhi, Tanikella Bharani",
          "worldwidegross": "59.1cr\n\nWorldwide Share",
          "imdbRating": "7.5"
        },
        {
          "id": "top_grossing_telugu_000175",
          "name": "Raja the Great",
          "synopsis": "Raja who is born blind but has extraordinary senses and is a trained skillful fighter is assigned to rescue a girl.",
          "releaseYear": "2017",
          "moviegenre": "Action, Comedy",
          "director": "Anil Ravipudi",
          "cast": "Ravi Teja, Mehreen Pirzada, Vivan Bhatena, Radhika Sarathkumar",
          "worldwidegross": "56.6cr\n\nWorldwide Share",
          "imdbRating": "6.5"
        },
        {
          "id": "top_grossing_telugu_000176",
          "name": "Shatamanam Bhavati",
          "synopsis": "The anguish that negligent children can cause is depicted here from the parents' perspective.",
          "releaseYear": "2017",
          "moviegenre": "Drama",
          "director": "Satish Vegesna",
          "cast": "Sharwanand, Anupama Parameswaran, Prakash Raj, Jayasudha",
          "worldwidegross": "55cr\n\nWorldwide Share",
          "imdbRating": "7.1"
        },
        {
          "id": "top_grossing_telugu_000177",
          "name": "1: Nenokkadine",
          "synopsis": "A rock star must overcome his psychological inhibitions to seek revenge for his parents' death.",
          "releaseYear": "2014",
          "moviegenre": "Action, Thriller",
          "director": "Sukumar",
          "cast": "Mahesh Babu, Kriti Sanon, Nassar, Pradeep Singh Rawat",
          "worldwidegross": "53.8cr\n\nWorldwide Share",
          "imdbRating": "8.1"
        },
        {
          "id": "top_grossing_telugu_000178",
          "name": "Ramayya Vastavayya",
          "synopsis": "Nandu a happy go lucky boy falls in love with Akarsha (Samantha) only to avenge his fiance's death.",
          "releaseYear": "2013",
          "moviegenre": "Action, Drama",
          "director": "Harish Shankar",
          "cast": "N.T. Rama Rao Jr., Samantha Ruth Prabhu, Shruti Haasan, P. Ravi Shankar",
          "worldwidegross": "53.8cr\n\nWorldwide Share",
          "imdbRating": "5.1"
        },
        {
          "id": "top_grossing_telugu_000179",
          "name": "Simha",
          "synopsis": "A Tale of Father and Son who brings down Injustice in their reign.",
          "releaseYear": "2010",
          "moviegenre": "Action, Drama",
          "director": "Boyapati Srinu",
          "cast": "Nandamuri Balakrishna, Ali, Saira Banu, Krishna Bhagavan",
          "worldwidegross": "53.7cr\n\nWorldwide Share",
          "imdbRating": "5.9"
        },
        {
          "id": "top_grossing_telugu_000180",
          "name": "Badrinath",
          "synopsis": "Badri, a warrior and the protector of Badrinath temple, finds himself in troubled waters after an agnostic woman falls for him and his mentor suspects him of loving her back.",
          "releaseYear": "2011",
          "moviegenre": "Action, Drama, Romance",
          "director": "V.V. Vinayak",
          "cast": "Allu Arjun, Tamannaah Bhatia, Prakash Raj, Kelly Dorji",
          "worldwidegross": "53.7cr\n\nWorldwide Share",
          "imdbRating": "4.4"
        },
        {
          "id": "top_grossing_telugu_000181",
          "name": "Iddarammayilatho",
          "synopsis": "A young woman becomes embroiled in a financial and political conspiracy while studying in Spain, as she meets a young musician with a somewhat dark past unfolded through the pages of his lover's diary.",
          "releaseYear": "2013",
          "moviegenre": "Action, Romance",
          "director": "Puri Jagannadh",
          "cast": "Allu Arjun, Amala Paul, Catherine Tresa, Nassar",
          "worldwidegross": "53.6cr\n\nWorldwide Share",
          "imdbRating": "5.8"
        },
        {
          "id": "top_grossing_telugu_000182",
          "name": "Brindaavanam",
          "synopsis": "Krish (NTR) is the son of a billionaire businessman (mukesh Rishi). He has a girl friend Indu (samantha). Her friend Bhoomi (kajal) wants to pursue her higher studies and lands in trouble.",
          "releaseYear": "2010",
          "moviegenre": "Action, Comedy, Drama",
          "director": "Vamshi Paidipally",
          "cast": "N.T. Rama Rao Jr., Kajal Aggarwal, Samantha Ruth Prabhu, Prakash Raj",
          "worldwidegross": "52.5cr\n\nWorldwide Share",
          "imdbRating": "7.1"
        },
        {
          "id": "top_grossing_telugu_000183",
          "name": "Yamadonga",
          "synopsis": "A lovable scoundrel's life is cut short when he angers the god of death; however, he still has a few tricks up his sleeve.",
          "releaseYear": "2007",
          "moviegenre": "Action, Comedy, Fantasy",
          "director": "S.S. Rajamouli",
          "cast": "N.T. Rama Rao Jr., Mohan Babu, Priyamani, Mamta Mohandas",
          "worldwidegross": "51.8cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000184",
          "name": "Jersey",
          "synopsis": "A failed cricketer decides to revive his cricketing career in his late 30's despite everyone being skeptical of his ability to do so.",
          "releaseYear": "2019",
          "moviegenre": "Drama, Sport",
          "director": "Gowtam Tinnanuri",
          "cast": "Nani, Shraddha Srinath, Sathyaraj, Harish Kalyan",
          "worldwidegross": "51.7cr\n\nWorldwide Share",
          "imdbRating": "8.6"
        },
        {
          "id": "top_grossing_telugu_000185",
          "name": "Arjun Reddy",
          "synopsis": "Arjun Reddy, a short tempered house surgeon gets used to drugs and drinks when his girlfriend is forced to marry another person.",
          "releaseYear": "2017",
          "moviegenre": "Action, Drama, Romance",
          "director": "Sandeep Reddy Vanga",
          "cast": "Vijay Deverakonda, Shalini Pandey, Jia Sharma, Kanchana",
          "worldwidegross": "51.5cr\n\nWorldwide Share",
          "imdbRating": "8.1"
        },
        {
          "id": "top_grossing_telugu_000186",
          "name": "Jalsa",
          "synopsis": "Sanjay, a young man, joins an extremist group after having had a troublesome childhood. A policeman decides to guide him towards a far better path and in doing so, his daughter falls crazy with Sanjay.",
          "releaseYear": "2008",
          "moviegenre": "Action, Comedy",
          "director": "Trivikram Srinivas",
          "cast": "Pawan Kalyan, Ileana D'Cruz, Mukesh Rishi, Kamalinee Mukherjee",
          "worldwidegross": "51.3cr\n\nWorldwide Share",
          "imdbRating": "7.3"
        },
        {
          "id": "top_grossing_telugu_000187",
          "name": "Bheeshma",
          "synopsis": "Bheeshma is a young bachelor who is desperate to find a girlfriend. One day, he meets and falls in love with Chaitra, who works for an organics company that coincidentally carries his first name.",
          "releaseYear": "2020",
          "moviegenre": "Action, Comedy, Romance",
          "director": "Venky Kudumula",
          "cast": "Nithiin, Rashmika Mandanna, Rajiv Kumar A., Ajay",
          "worldwidegross": "51.2cr\n\nWorldwide Share",
          "imdbRating": "6.6"
        },
        {
          "id": "top_grossing_telugu_000188",
          "name": "Indra",
          "synopsis": "Since 1965 bitter hatred and animosity has reigned between two families, namely that of Indrasen's and the Reddys, which results in the death of Indrasen's dad, and his two uncles.",
          "releaseYear": "2002",
          "moviegenre": "Action, Drama",
          "director": "Gopal B.",
          "cast": "Chiranjeevi, Sonali Bendre, Aarthi Agarwal, Prakash Raj",
          "worldwidegross": "51.1cr\n\nWorldwide Share",
          "imdbRating": "7.4"
        },
        {
          "id": "top_grossing_telugu_000189",
          "name": "Rarandoi Veduka Chudham",
          "synopsis": "While attending a wedding, a gregarious young man falls in love with a stubborn woman.",
          "releaseYear": "2017",
          "moviegenre": "Action, Romance",
          "director": "Kalyan Krishna",
          "cast": "Avantika, Rakul Preet Singh, Naga Chaitanya Akkineni, Jagapathi Babu",
          "worldwidegross": "51cr\n\nWorldwide Share",
          "imdbRating": "5.6"
        },
        {
          "id": "top_grossing_telugu_000190",
          "name": "Shankar Dada MBBS",
          "synopsis": "A doctor treats patients with humanity (not with medicines).",
          "releaseYear": "2004",
          "moviegenre": "Comedy",
          "director": "Jayant Paranji",
          "cast": "Chiranjeevi, Meka Srikanth, Sonali Bendre, Paresh Rawal",
          "worldwidegross": "50.7cr\n\nWorldwide Share",
          "imdbRating": "7.4"
        },
        {
          "id": "top_grossing_telugu_000191",
          "name": "Stalin",
          "synopsis": "The story is about how an ex-army officer brings change in society by making people to help each other.",
          "releaseYear": "2006",
          "moviegenre": "Action, Drama",
          "director": "A.R. Murugadoss",
          "cast": "Chiranjeevi, Trisha Krishnan, Prakash Raj, Sharada",
          "worldwidegross": "50.3cr\n\nWorldwide Share",
          "imdbRating": "6"
        },
        {
          "id": "top_grossing_telugu_000192",
          "name": "Tagore",
          "synopsis": "Ravindranath Tagore, a physics professor, forms the ACF [Anti Corruption Force] along with his former students to take on corruption in society.",
          "releaseYear": "2003",
          "moviegenre": "Action, Drama",
          "director": "V.V. Vinayak",
          "cast": "Chiranjeevi, Jyotika, Shriya Saran, Suneel",
          "worldwidegross": "50.1cr\n\nWorldwide Share",
          "imdbRating": "7.8"
        },
        {
          "id": "top_grossing_telugu_000193",
          "name": "Jai Simha",
          "synopsis": "A rowdy mechanic with a golden-heart turns into a body guard to save a family from goons.",
          "releaseYear": "2018",
          "moviegenre": "Action, Comedy, Drama",
          "director": "K.S. Ravikumar",
          "cast": "Nandamuri Balakrishna, Nayanthara, Haripriya, Natasha Doshi",
          "worldwidegross": "50cr\n\nWorldwide Share",
          "imdbRating": "4.8"
        },
        {
          "id": "top_grossing_telugu_000194",
          "name": "Nene Raju Nene Mantri",
          "synopsis": "Radha jogendhra journey to the Chief Minister position and what inspired him to go after political power.",
          "releaseYear": "2017",
          "moviegenre": "Action, Thriller",
          "director": "Teja",
          "cast": "Mahesh Achanta, Kajal Aggarwal, Ajay, Rajsekhar Aningi",
          "worldwidegross": "50cr\n\nWorldwide Share",
          "imdbRating": "5.9"
        },
        {
          "id": "top_grossing_telugu_000195",
          "name": "Bhale Bhale Magadivoy",
          "synopsis": "An easily distracted scientist (Nani) goes to great lengths to make sure that his girlfriend (Lavanya Tripati) and her family members don't find out about his mental condition.",
          "releaseYear": "2015",
          "moviegenre": "Comedy, Romance",
          "director": "Maruthi Dasari",
          "cast": "Nani, Lavanya Tripathi, Praveen, Ajay",
          "worldwidegross": "50cr\n\nWorldwide Share",
          "imdbRating": "7.7"
        }
      ]